---

- name: Use ChatGPT module
  hosts: localhost
  gather_facts: no

  vars_files:
    - secrets.yml

  tasks:

    - name: Query ChatGPT
      chatgpt:
        query: "Explain the concept of Ansible modules."
        api_key: "{{ openai_api_key }}"
        #model: "gpt-3.5-turbo"
        max_tokens: 10
      register: result

    - name: Print ChatGPT response
      ansible.builtin.debug:
        msg: "{{ result.response }}"

